tcp:

  routers:

    serverhome-router:
      entryPoints:
        - websecure  # This should match the entrypoint for 443
      rule: "HostSNIRegexp(`^.+\\.serverhome\\.info`)"
      service: serverhome-service
      tls:
        passthrough: true        

    tophomelab-router:
      entryPoints:
        - websecure  # This should match the entrypoint for 443
      rule: "HostSNIRegexp(`^.+\\.tophomelab\\.work`)"
      service: tophomelab-service
      tls:
        passthrough: true   

  services:
  
    serverhome-service:
      loadBalancer:
        servers:
          - address: "10.0.5.111:443"  # Forward traffic to the VM     

    tophomelab-service:
      loadBalancer:
        servers:
          - address: "10.0.6.101:443"  # Forward traffic to the VM               


